various

diff --git a/.fluxbox/startup b/.fluxbox/startup
--- a/.fluxbox/startup
+++ b/.fluxbox/startup
@@ -80,23 +80,43 @@ fi
 
 	lxpanel &
 	/opt/trinity/bin/kicker &
-
-	# If we wait longer, the nm-applet will be placed in the lxpanel instead of the Flubbox panel.
-	sleep 2
+	# If we wait a bit longer, the nm-applet will be placed in the lxpanel instead of the Flubbox panel.
+	#sleep 2
 
 	nm-applet &
 
-	sleep 2
+	# Something is starting gnome-screensaver.  I think it might be nm-applet but I'm not sure.
+	# I don't want gnome-screensaver if I have xscreensaver running, because I end up having to unlock twice!
+	( sleep 20 ; pgrep -u $UID xscreensaver && killall gnome-screensaver ) &
+	# Possibly if I started xscreensaver later, or gnome-screensaver explicitly, one would disable the other.  But currently this is not happening.
 
-	xscreensaver -no-splash &
+	sleep 1
 
-	sleep 2
+	(
+		# If I try to do this too early, there is no ibus running to replace!
+		sleep 5
 
-	# I was doing this earlier, but it was getting reset by something!
-	# On Ubuntu 14.04 (upgraded from 12.04), /etc/default/keyboard is not being respected by X, so we force it here:
-	. /etc/default/keyboard
-	#[ -z "$XKBLAYOUT" ] && XKBLAYOUT=gb
-	[ -n "$XKBLAYOUT" ] && setxkbmap "$XKBLAYOUT"
+		# Note that this should be done before running setxkbmap, because it resets it!
+		if pgrep -u $UID ibus-daemon >/dev/null
+		then
+			echo "Restarting ibus-daemon in synchronous mode" >&2
+			#IBUS_ENABLE_SYNC_MODE=1 ibus-daemon -xrd
+			# Apparently an alternative is to run it without --xim:
+			IBUS_ENABLE_SYNC_MODE=0 ibus-daemon --replace --verbose -d
+			# Neither of the above worked for me! :P
+		else
+			echo "I cannot restart ibus-daemon because Ubuntu hasn't started it yet!" >&2
+		fi
+
+		sleep 1
+
+		# I was doing this earlier, but it was getting reset by something!  (Not us running ibus-daemon, but perhaps Ubuntu running it?)
+		# On Ubuntu 14.04 (upgraded from 12.04), /etc/default/keyboard is not being respected by X, so we force it here:
+		. /etc/default/keyboard
+		#[ -z "$XKBLAYOUT" ] && XKBLAYOUT=gb
+		[ -n "$XKBLAYOUT" ] && setxkbmap "$XKBLAYOUT"
+
+	) &
 
 	# Later I will probably start gnome-settings-daemon, otherwise Chrome's font size will be awful.
 	# But that will take over screen locking, and will mess up my keyboard repeat speed when unlocking.
@@ -105,6 +125,10 @@ fi
 	# It works, but only after Gnome interface is used to unlock.
 	# But I discovered my settings are lost more often that - whenever the machine resumes from suspend.
 	# So I started using this instead: /etc/pm/sleep.d/50_restore_joeys_x_settings
+
+	sleep 2
+
+	xscreensaver -no-splash &
 
 ) &
 
